# Generated by Django 4.2.16 on 2025-06-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myINT', '0002_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='category',
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(related_name='blogs', to='myINT.category'),
        ),
    ]
