# Generated by Django 4.2.16 on 2025-06-19 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myINT', '0008_remove_blog_categories_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='category',
            new_name='categories',
        ),
    ]
