# Generated by Django 4.2.16 on 2025-06-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myINT', '0010_remove_blog_categories_blog_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
