# Generated by Django 4.2.16 on 2025-08-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myINT', '0012_tag_blog_created_at_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
